# Generated by Django 5.1.4 on 2025-01-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_draftdb_drafthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramTemplateDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('FOOTER', 'footer'), ('HEADER', 'header'), ('MIDDLE', 'middle')], max_length=10)),
                ('text', models.TextField()),
            ],
        ),
    ]
