# Generated by Django 5.1.4 on 2025-02-03 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_telegramtemplatedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtemplatedb',
            name='title',
            field=models.CharField(default='title', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channeldb',
            name='last_refresh',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drafthistory',
            name='edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
