# Generated by Django 5.1.4 on 2025-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_draftdb_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftdb',
            name='media_url',
            field=models.JSONField(null=True),
        ),
    ]
