version: '3'

volumes:
  media:
  redis_data:
  pg_data:
  tg_session:

services:
  redis:
      image: redis:7-alpine
      volumes:
        - redis_data:/data
      ports:
        - 6379:6379
  db:
    image: postgres:13
    env_file: 
      - .env.prod
    volumes: 
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env.prod
    volumes:
      - media:/app/media
      - tg_session:/app/session
    depends_on:
      - db

  frontend:
    build: ./frontend/
    image: faridaily_frontend:latest
    env_file: .env.prod
  
  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: poetry run celery -A backend worker -l INFO
    env_file: .env.prod
    volumes:
      - media:/app/media
      - tg_session:/app/session
    depends_on:
      - redis
      - backend
      - db

  celery-beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: poetry run celery -A backend beat -l INFO
    env_file: .env.prod
    volumes:
      - media:/app/media
      - tg_session:/app/session
    depends_on:
      - redis
      - backend
      - db
  
  gateway:
    build: ./nginx/
    env_file: .env.prod
    ports:
      - 8020:80
    volumes:
      - media:/media/
    depends_on:
      - backend
      - frontend

