name: Main Faridaily Workflow

on:
    push:
      branches:
        - main
jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: "True"
        ALLOWED_HOSTS: "127.0.0.1,localhost"
        TG_API_HASH: ${{ secrets.TG_API_HASH }}
        TG_API_ID: ${{ secrets.TG_API_ID }}
        TG_CHANNEL_TOKEN: ${{ secrets.TG_CHANNEL_TOKEN }}
        TG_TEST_CHANNEL_TOKEN: ${{ secrets.TG_TEST_CHANNEL_TOKEN }}
        CHANNEL_NAME: "albumsweekly"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run tests
        run: poetry run pytest -p no:warnings --verbose
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: frailtynine/faridaily-backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: frailtynine/faridaily-frontend:latest

      - name: Build and push Nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: frailtynine/faridaily-nginx:latest

